### ISSUE TITLE
Please provide attribution to starkscan-verifier as required by the AGPL license

### ISSUE THREAD

**Issue by 0xs34n** [NethermindEth/voyager-verify#1]
Please leave an attribution for the starkscan verifier (https://github.com/starkscan/starkscan-verifier) as required by the AGPL license. Thank you.

**Comment by Bart-Do** [comment]
@0xs34n Could you share explicitly, what it is about our code that makes you think it is derived from the repository you linked?

**Comment by 0xs34n** [comment]
Can you confirm that you did not read the code of starkscan-verifier to build your verifier?

**Comment by JorikSchellekens** [comment]
Hello @0xs34n!

We had a ticket prior to our knowledge of StarkScan to create a cli tool, imo it is the most logical way to interact with contract verification and I was very glad to see StarkScan lead the way with it. When yours launched we prioritised ours!

Our implementation is not a Verbatim, Modified Source or Object Code copy of your work so doesn't fall under the requirements of the AGPL. Significantly, the requirement to preserve the StarkScan copyright notice does not apply to our work.

We wish you all the success in building an amazing block explorer and we're looking forward to participating with you in building up the StarkNet ecosystem. I'm looking forward to collaborating on ideas with you for the improvement, promotion and adoption of StarkNet.

We're very impressed with StarkScan and are excited to see what you come up with next :)
